version: '3.4'

services:
  firstapi:
    image: firstapi
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    links:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    ports:
      - 8081:8081
    links:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro